[package]
name = "foxbox_thinkerbell"
version = "0.1.2"
authors = ["David Rajchenbach-Teller <dteller@mozilla.com>"]

[dependencies]
serde = "0.6.13"
serde_json = "0.6.0"
serde_macros = "0.6.14"
chrono = "0.2.19"
foxbox_taxonomy = { git = "https://github.com/fxbox/taxonomy.git" }
foxbox_adapters = { git = "https://github.com/fxbox/adapters.git" }
# foxbox_adapters = { path = "../adapters" }
# foxbox_taxonomy = { path = "../taxonomy" }
rusqlite = "0.6.0"
transformable_channels = "*"

[dev-dependencies]
docopt = "0.6.78"
