[package]
name = "fxbox_thinkerbell"
version = "0.1.1"
authors = ["David Rajchenbach-Teller <dteller@mozilla.com>"]

[dependencies]
serde = "0.6.13"
serde_json = "0.6.0"
serde_macros = "0.6.14"
chrono = "0.2.19"
fxbox_taxonomy = { git = "https://github.com/fxbox/taxonomy.git",  rev="83bd0d9" }

[dev-dependencies]
docopt = "0.6.78"
