language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

script:
  - cargo build
  # FIXME: We currently execute unit tests twice. Once with and the other time,
  # without the dead code in the binary.
  - cargo test -- --nocapture
  - $TRAVIS_BUILD_DIR/tools/execute-unit-tests-with-coverage

rust:
  - nightly-2016-04-10
